apiVersion: batch/v1
kind: Job
metadata:
  name: "{replaced with MLflow Project name}"
  namespace: METTEZ_ICI_VOTRE_NAMESPACE
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: "{replaced with MLflow Project name}"
          image: "{replaced with URI of Docker image created during Project execution}"
          command: ["{replaced with MLflow Project entry point command}"]
          resources:
            limits:
              cpu: 1300m
              memory: 4000Mi
            requests:
              cpu: 1300m
              memory: 4000Mi
      restartPolicy: Never