name: Cats and dogs CI/CD

on:
  push:
    branches:
      - step**

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r cats_dogs_other/requirements.txt

      - name: Run training script
        run: |
          python cats_dogs_other/train/train.py \
            --split_ratio_train 0.7 \
            --split_ratio_evaluate 0.15 \
            --split_ratio_test 0.15 \
            --working_dir /tmp/cats_dogs_other
